Update deployment workflow for dynamic environments
Refactor deployment workflow to support dynamic environments and version validation.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,88 +1,122 @@
-name: Promotional Deployment
+name: Deploy
+
+env:
+  INSTALLER_PRODUCT_NAME: Straumann-SIRIOS
 
 on:
   workflow_dispatch:
     inputs:
-      manualRunId:
-          description: 'Run ID of the build to deploy (leave blank for latest)'
-          required: false
-          type: string
-      isMandatoryUpdate:
-        description: 'Is this a mandatory update?'
+      deployEnvironment:
+        description: 'Target environment'
         required: true
-        type: boolean
+        default: 'staging'
+        type: choice
+        options: [ dev, test, staging ]
+      mandatory:
+        description: 'Mandatory version'
         default: false
+        type: boolean
+      version:
+        description: 'Type version to deploy in format: X.X.X.X'
+        required: true
+        type: string
 
 jobs:
-  deploy-staging:
-    name: Deploy to Staging
-    runs-on: ubuntu-latest
+  non-prod-deploy:
+    name: Deploy to ${{ github.event.inputs.deployEnvironment }}
+    if: |
+      github.event.inputs.deployEnvironment == 'dev' || 
+      github.event.inputs.deployEnvironment == 'test'
+    runs-on: 'ubuntu-latest'
+    environment: ${{ github.event.inputs.deployEnvironment }}
+    permissions:
+      contents: read
+
+    steps:
+      - name: Parse and Validate Version
+        id: installer-file-name
+        run: |
+          RAW_VERSION="${{ github.event.inputs.version }}"
+          CLEAN_VERSION=$(echo "$RAW_VERSION" | xargs)
+
+          SEMVER_REGEX="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
+
+          if [[ ! $CLEAN_VERSION =~ $SEMVER_REGEX ]]; then
+            echo "::error::Invalid version format: $CLEAN_VERSION. Expected X.X.X.X"
+            exit 1
+          fi
+
+          INSTALLER_FILE_NAME=${INSTALLER_PRODUCT_NAME}-${CLEAN_VERSION}.exe
+
+          echo "VERSION=${CLEAN_VERSION}" >> $GITHUB_ENV
+          echo "INSTALLER_FILE_NAME=${INSTALLER_FILE_NAME}" >> $GITHUB_ENV
+          echo "Installer to deploy: $INSTALLER_FILE_NAME"
+          echo "environment? ${{ github.event.inputs.deployEnvironment }}"
+          echo "Is mandatory? ${{ github.event.inputs.mandatory }}"
+
+  staging:
+    name: Deploy to staging
+    runs-on: 'ubuntu-latest'
     environment: staging
+    permissions:
+      contents: read
+    outputs:
+      installer-file-name: ${{ steps.installer-file-name.outputs.INSTALLER_FILE_NAME }}
+      installer-version: ${{ steps.installer-file-name.outputs.VERSION }}
+
     steps:
-      - name: Determine Run ID
-        id: select-run
+      - name: Parse and Validate Version
+        id: installer-file-name
         run: |
-          # Check if the user provided a manual ID
-          USER_INPUT="${{ github.event.inputs.manualRunId }}"
-          
-          if [ -n "$USER_INPUT" ]; then
-            echo "Using manually provided Run ID: $USER_INPUT"
-            echo "final_run_id=$USER_INPUT" >> $GITHUB_OUTPUT
-          else
-            echo "No Run ID provided. Fetching latest successful build..."
-            RUN_ID=$(gh run list --repo ${{ github.repository }} --workflow "build.yml" --branch main --status success --limit 1 --json databaseId --jq '.[0].databaseId')
-            
-            if [ "$RUN_ID" = "null" ] || [ -z "$RUN_ID" ]; then
-              echo "Error: No successful build runs found!"
-              exit 1
-            fi
-            
-            echo "Found latest Run ID: $RUN_ID"
-            echo "final_run_id=$RUN_ID" >> $GITHUB_OUTPUT
+          RAW_VERSION="${{ github.event.inputs.version }}"
+          CLEAN_VERSION=$(echo "$RAW_VERSION" | xargs)
+
+          SEMVER_REGEX="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
+
+          if [[ ! $CLEAN_VERSION =~ $SEMVER_REGEX ]]; then
+            echo "::error::Invalid version format: $CLEAN_VERSION. Expected X.X.X.X"
+            exit 1
           fi
+
+          INSTALLER_FILE_NAME=${INSTALLER_PRODUCT_NAME}-${CLEAN_VERSION}.exe
+
+          echo "VERSION=${CLEAN_VERSION}" >> $GITHUB_ENV
+          echo "INSTALLER_FILE_NAME=${INSTALLER_FILE_NAME}" >> $GITHUB_ENV
+          echo "Installer to deploy: $INSTALLER_FILE_NAME"
+          echo "environment? ${{ github.event.inputs.deployEnvironment }}"
+          echo "Is mandatory? ${{ github.event.inputs.mandatory }}"
+
+  release-candidate:
+    name: Release candidate
+    needs: staging
+    runs-on: 'ubuntu-latest'
+    environment: pre-prod
+    env:
+      INSTALLER_FILE_NAME: ${{ needs.staging.outputs.installer-file-name }}
+    outputs:
+      installer-file-name: ${{ needs.staging.outputs.installer-file-name }}
+      installer-version: ${{ needs.staging.outputs.installer-version }}
+
+    steps:
+      - name: Download artifact
         env:
-          GH_TOKEN: ${{ github.token }}
-
-      - name: Download Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: production-artifact
-          run-id: ${{ steps.select-run.outputs.final_run_id }}
-          github-token: ${{ github.token }}
-
-      - name: Deploy
+          RETRY_COUNT: 3
         run: |
-          echo "Deploying Artifact from Run ID: ${{ steps.select-run.outputs.final_run_id }}"
-          echo "Mandatory Update: ${{ inputs.isMandatoryUpdate }}"
+          echo "Successfully downloaded ${{ env.INSTALLER_FILE_NAME }}"
+          echo "Successfully downloaded version ${{ needs.staging.outputs.installer-version }}"
 
-  deploy-preprod:
-    name: Deploy to Pre-Prod
-    needs: deploy-staging
-    runs-on: ubuntu-latest
-    environment: preprod
+  release:
+    name: Release
+    needs: release-candidate
+    runs-on: 'ubuntu-latest'
+    environment: prod
+    env:
+      INSTALLER_FILE_NAME: ${{ needs.release-candidate.outputs.installer-file-name }}
+
     steps:
-      - name: Download Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: production-artifact
-
-      - name: Deploy
-        run: echo "Deploying to Pre-Prod..."
-
-  deploy-prod:
-    name: Deploy to Production
-    needs: deploy-preprod
-    runs-on: ubuntu-latest
-    environment: production
-    steps:
-      - name: Download Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: production-artifact
-
-      - name: Final Deploy
+      - name: Download artifact
+        env:
+          RETRY_COUNT: 3
         run: |
-          echo "Deploying to Production"
-          if [ "${{ inputs.isMandatoryUpdate }}" = "true" ]; then
-            echo "Executing high-priority migration scripts..."
-          fi
+          echo "Successfully downloaded ${{ env.INSTALLER_FILE_NAME }}"
+          echo "Successfully downloaded version ${{ needs.release-candidate.outputs.installer-version }}"
